### ISSUE TITLE
Codespaces Localstack CDN_URL refuses to connect.

### ISSUE THREAD

**Issue by JeroenJADS** [run-llama/sec-insights#22] opened 2023-09-11 15:17 UTC
I ran the entire repository in Github CodeSpaces, and everything works perfectly. However, when opening a Conversation the frontend gives the error " https://llama-app-web-assets-local.s3-website.localhost.localstack.cloud:4566/sec-edgar-filings/0001018724/10-K/0001018724-21-000004/filing-details.pdf net::ERR_CONNECTION_REFUSED. It seems the routing doesn't work properly? 

In addition, I had to change the NEXT_PUBLIC_BACKEND_URL=http://localhost:8000, to the actual URL of the Github Codespace. Not sure if that's required but that's the only way it worked for me.

Anyone else got this problem?

**Comment by sourabhdesai** [comment] 2023-09-12 02:41
@JeroenJADS thanks for raising this!

I believe the commands for setting up the localstack bucket under [`make seed_db_local` here](https://github.com/run-llama/sec-insights/blob/3e5d162/backend/Makefile#L57-L64) would also need to be run.

I believe this would also require the installation of the `aws` CLI. Let me update the docs to include this as a setup instruction. I'll also section out those localstack bucket setup commands into a separate make command.

In the meantime, you can try running those commands yourself and see if that helps!

**Comment by sourabhdesai** [comment] 2023-09-12 02:48
Actually, I'm guessing you already ran the seed script to get the point where you want to see PDFs on your frontend? In which case, your localstack setup may not be the issue.

Perhaps it has to do with your use of Github Codespaces. Are you interacting with your codespace from the browser-based VS Code or are you connecting to your Codespace through your installed VS Code IDE? If the former, you probably need to switch to the latter of using Codespace through your local installation of VS code. That way you get the local port-forwarding based network setup that only the locally installed VS code can setup for you.

**Comment by sourabhdesai** [comment] 2023-09-12 02:56
Ended up separating out those localstack commands into a separate make command anyways ([PR](https://github.com/run-llama/sec-insights/pull/26)) even though it may not actually end up being the root cause behind your issue

**Comment by sourabhdesai** [comment] 2023-09-12 22:22
Closing the issue as there's no follow-up. Please re-open if you continue having an issue related to this!

**Closed by sourabhdesai** 2023-09-12 22:22 UTC
